### ISSUE TITLE
metoden erLevertTilPostkasse() henviser til Leveringskvitteringer som også brukes for fysisk post

### ISSUE THREAD

**Issue by aberner** [digipost/sdp-shared#4]
ref: https://github.com/digipost/sdp-shared/blob/master/api-commons/src/main/java/no/digipost/api/representations/SimpleStandardBusinessDocument.java#L160

Metodenavnet som er definert er: 

- public boolean erLevertTilPostkasse()

Denne metoden brukes av Avsender for å sjekke om kvitteringen er av type Leveringskvittering.
Leveringskvitteringer brukes både i for digital post og for fysisk post. 
Dette betyr at metodenavnet er noe misvisende og burde ha hat samme navnkonvensjon som de andre metodene, f.eks bare: erLevert()

**Comment by asjafjell** [comment]
Denne metoden er nå ikke tilgjengelig for databehandler. Nå sjekker databehandler hvilke kvitteringer som kommer.
